server:
  port: 8080
#spring.cloud.gateway.discovery.locator.lower-case-service-id=true
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      #      discovery:
      #        locator:
      #          enabled: true
      #          lowerCaseServiceId: true

      routes:
        - id: login-service
          uri: lb://login-service
          predicates:
#           if it didn't work use /login-service/api/users/**
            - Path=/api/users/**
            - Method=GET,PUT,DELETE
            - Header=Authorization, Bearer (.*)
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/users-service/api/users, /api/users
#          execute this filter before this route is executed if login fail this route won't execute
            - AuthorizationHeaderFilter

        - id: user-login
          uri: lb://login-service
          predicates:
            - Path=/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/users-service/api/users, /api/users

        - id: login-service-create
          uri: lb://login-service/api/users
          predicates:
            - Path=/api/users
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/users-service/api/users, /api/users

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

#the same token we heve in login .yml
token:
  secret: H3(KVfajgJReaZeQb7cdrqBeZfgchvPhkigae2PhjVkYWRlPumnc1wko4pqresDd