server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://naming-server:8761/eureka
spring:
  application:
    name: student-service
  #database configuration
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://shared-db:3306/student_service?useTimezone=true&serverTimezone=UTC
    username: docker
    password: admin123

  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update

  flyway:
    url: jdbc:mysql://shared-db:3306
    schemas: student_service
    user: docker
    password: admin123

#swagger paths definitions
spring-doc:
  pathsToMatch: /api/**
  swagger-ui:
    use-root-path: true

