CREATE DATABASE IF NOT EXISTS course_service;
CREATE DATABASE IF NOT EXISTS grade_service;
CREATE DATABASE IF NOT EXISTS login_service;
CREATE DATABASE IF NOT EXISTS parent_service;
CREATE DATABASE IF NOT EXISTS student_service;
CREATE DATABASE IF NOT EXISTS teacher_service;
