server:
  port: 8085
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: grade-service
  #database configuration
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/grade_service?useTimezone=true&serverTimezone=UTC
    username: root
    password: root

  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update

  flyway:
    url: jdbc:mysql://localhost:3306
    schemas: grade_service
    user: root
    password: root
