server:
  port: 8083
eureka:
  client:
    service-url:
      defaultZone: http://naming-server:8761/eureka
spring:
  application:
    name: teacher-service
  #database configuration
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://shared-db:3306/teacher_service?useTimezone=true&serverTimezone=UTC
    username: docker
    password: admin123

  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update

  flyway:
    url: jdbc:mysql://shared-db:3306
    schemas: teacher_service
    user: docker
    password: admin123
